=== julleb/ServerMonitor/information.dtd
<!ELEMENT informations (information*, Min*, Max*) >
<!ELEMENT information (Date, CPU*, Memory*) >
<!ELEMENT Date (#PCDATA) >
<!ELEMENT CPU (ServerData*)>
<!ELEMENT Memory (ServerData*)>
<!ELEMENT ServerData (Description, value)>
<!ATTLIST ServerData unit CDATA #IMPLIED>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT Max (#PCDATA)>
<!ELEMENT Min (#PCDATA)>

<!ENTITY degree "&#176;">

=== julleb/ServerMonitor/fake.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE informations SYSTEM "information.dtd">
<?xml-stylesheet type="text/xsl" href="xslt-fake.xsl"?>


<informations>
    <information>
        <Date>2015-09-30T16:28:32</Date>
        <CPU>
            <ServerData unit="C">
                <Description>Temperature</Description>
                <value>61</value>
            </ServerData>
            <ServerData unit="%">
                <Description>Load</Description>
                <value>99</value>
            </ServerData>
        </CPU>
        <Memory>
            <ServerData unit="M">
                <Description>Total</Description>
                <value>7839</value>
            </ServerData>
            <ServerData unit="M">
                <Description>Used</Description>
                <value>2576</value>
            </ServerData>
        </Memory>
    </information>

</informations>
